### ISSUE TITLE
[Question] How does one use Turbolinks in an Android application with tabs?

### ISSUE THREAD

**Issue by joemasilotti** [turbolinks/turbolinks-android#10]
More specifically, can one create multiple `TurbolinksSession` instances managed by a single `ViewPager`?

From [the documentation](http://turbolinks.github.io/turbolinks-android/javadoc/), a `TurbolinksSession` is created with a reference to an `Activity`. 

```java
/**
 * <p><b>REQUIRED</b> Turbolinks requires a context for a variety of uses, and for maximum clarity
 * we ask for an Activity context instead of a generic one. (On occassion, we've run into WebView
 * bugs where an Activity is the only fix).</p>
 *
 * <p>It's best to pass a new activity to Turbolinks for each new visit for clarity. This ensures
 * there is a one-to-one relationship maintained between internal activity IDs and visit IDs.</p>
 *
 * @param activity An Android Activity, one per visit.
 * @return The TurbolinksSession to continue the chained calls.
 */
public TurbolinksSession activity(Activity activity)
```

To create a `ViewPager`, the building block for switching between views, one must configure an adapter, `PagerAdapter`. According to [Google's documentation](http://developer.android.com/reference/android/support/v4/view/PagerAdapter.html), there are only two known subclasses, both dealing with `Fragment`s.

To my understanding, a `Fragment` is not sufficient for Turbolinks, a full-fledged `Activity` is needed. And the `ViewPager` needs the opposite, just a `Fragment`.

Is there a workaround, for either framework, to have a `TabView` display multiple instances of the session?

**Comment by joemasilotti** [comment]
I noticed that the Basecamp app on Android is using tabs! So I'm either misunderstanding something or your team has build a very custom adapter.

**Comment by lateplate** [comment]
This should be feasible, though I can't say for sure without trying it.

Conceptually, you should be able to create multiple TurbolinksSession objects via `Turbolinks.getNew()`, and you could manage their lifecycles yourself. The activity you pass into Turbolinks should just be whatever activity you started from.

Instead of using one of the provided concrete implementations of ViewPager which are fragment-centric, you would need to subclass `PagerAdapter` to make your own adapter and use that to present your views.

**Comment by h1u2i3** [comment]
viewpager + webview

**Comment by joemasilotti** [comment]
Got it, thanks @lateplate and @h1u2i3!

**Comment by yunusemredilber** [comment]
I'm still having some problems with using fragments. @joemasilotti did you solve this problem ?
