### ISSUE TITLE
fcm notification 

### ISSUE THREAD

**Issue by Hatesh8** [turbolinks/turbolinks-android#104]
Does anyone tell me how can I manage notification from firebase? I actually wanna send a notification to the logged in user at turbolniks,I got my FCM key but how can I get that logged in user's account details like email or phone number?

**Comment by lateplate** [comment]
Turbolinks doesn't do anything with notifications/Firebase. I'd recommend starting with the Android/Firebase documentation for that.

**Comment by Hatesh8** [comment]
@lateplate I know turbolinks doesn't do anything with firebase or notification but actually, I wanna send a notification to those users who are logged in turbolinks but for sending notifications firstly I have to get user email which is stored in cookies so how can I get that?

**Comment by lateplate** [comment]
Cookies are outside of the scope of Turbolinks. Turbolinks uses a [`WebView`](http://turbolinks.github.io/turbolinks-android/com/basecamp/turbolinks/TurbolinksSession.html#getWebView--) under the hood, so you can access cookies for a given application using [`CookieManager`](https://developer.android.com/reference/android/webkit/CookieManager).
