### ISSUE TITLE
Still deprecated?

### ISSUE THREAD

**Issue by pillaiindu** [turbolinks/turbolinks-android#110]
When are you guys removing the [DEPRECATED] from it?

**Comment by basicBrogrammer** [comment]
Is v2.0 open source? I'd love to be able to contribute or at least test it to push it forward

**Comment by lateplate** [comment]
2.0 is still in active development internally, so it's not quite ready for public release. It's hard to give an exact timeline as we're making some deep, fundamental changes and trying out different approaches. I'd say at least a few months. Thanks.

**Comment by basicBrogrammer** [comment]
Good luck

**Comment by ye-lin-aung** [comment]
Any updates on this ? @lateplate

**Comment by rept** [comment]
Any updates on this or any insight into a timeline? @lateplate
