### ISSUE TITLE
Bridge Injection Failure

### ISSUE THREAD

**Issue by PGMacDesign** [turbolinks/turbolinks-android#112]
Good day basecamp team + Collaborators! 

First off, thanks for this lib and working on the Android v2, we appreciate it and are excited to see it!

I have an app that is utilizing turbolinks via a rails back-end + an Android / iOS front end. 
For 90-95% of our customers, things work just fine and I don't see any issues. 
Roughly 5-10% of our users though see random issues relating to how the Turbolinks webview operates. 

Specifically, I am seeing the callback `turbolinksDoesNotExist` fire off for these customers every time they load one of our pages. While normally this wouldn't be an issue, it is causing problems as it is preventing certain authentication headers from carrying over and users are seeing a **401** as a result. 

The weird thing is that these pages work fine for the vast majority of users and it seems like only a few are facing this issue, so I have to conclude it is either a device or webview (some version on a device) issue. 

I am working on getting some web logging in place to narrow down the scope of the problem and whether it is only certain devices / API levels / etc that are causing it, but from now it looks like it is a wide spread. 

As an aside, I did try putting in some logic to [my forked version](https://github.com/PGMacDesign/turbolinks-android/blob/master/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksSession.java) that will completely clear out the webview / Turbolinks session whenever this error is hit and reload it entirely, but the issue persists. 

Any ideas what may be causing the Bridge injection to fail each time? Is this part of why the v2 refactor is happening? I just don't want to try and make a hacky workaround if this was part of the main issue the led to a rewrite in the first place.

**Comment by lazaronixon** [comment]
I don't know if it is your problem, but I noticed that error pages like 401, 500, etc.. should always return a blank page with turbolinks.js instead of no content.

**Comment by PGMacDesign** [comment]
Well, it took some digging, but I got to the root of the problem. 

I outlined it [here](https://stackoverflow.com/questions/61417268/using-the-android-turbolinks-framework-how-do-i-mitigate-bridge-injection-failu) for any that want the details, but the short version is that if the Chrome web browser is uninstalled, disabled, or out of date, this exception will occur (at least in our situation).
