### ISSUE TITLE
requestFailedWithStatusCode not called on first request

### ISSUE THREAD

**Issue by harmdewit** [turbolinks/turbolinks-android#12]
I'm using the callback to redirect all unauthorized (401) users to the login page. Unfortunately the callback is not being called on the first request, only on subsequent requests. This results in an blank page.

Maybe turbolinks didn't get a chance to initialize?

This is pretty easily fixed by using another base url and controlling the flow in the server, but i would be nicer to control the flow in the app.

(I'm not a Android developer so I might be totally wrong here :grin:)

**Comment by h1u2i3** [comment]
I find out that the turbolinkssession have a webview, and when it first load url, it inject the `TurbolinksNative` javascript interface, and if the inject failed, then the adapter of the TurbolinksSession's adapter cann‘t work as expected.

So if we want make the turbolinkssession adapter work, we must make sure the `turbolinksIsReady` is true, and if the `turbolinksIsReady` is not true, we must destroy the turbolinksession and get another new session.

**Comment by h1u2i3** [comment]
#13

**Comment by lateplate** [comment]
First, sorry for the slow response.

@harmdewit Which callback are you listening for?

As a little background, the first request is considered a "cold boot" where the Android WebView is executing a standard `loadUrl`, after which the Turbolinks adapter is injected and used to execute subsequent requests.

If your very first request is throwing an error, the webView _should_ execute its [`onReceivedError()`](https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksSession.java#L81-L153) callback, which should trigger the corresponding [`TurbolinksAdapter.onReceivedError()`](https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksAdapter.java#L22) callback.

Android's WebView (and its callbacks) are finicky, so it's certainly possible something isn't working correctly, too.

**Comment by lateplate** [comment]
@harmdewit I'm going to close this for now, but if you have more questions please feel free to comment and I can re-open if needed. Thanks!

**Comment by harmdewit** [comment]
Sorry for the late reply.

I was using a `BASE_URL` that required a user to be logged in. On unauthorized requests the rails app returns a `head(status: 401)`. 

As pointed out by @h1u2i3, if the first request has no page to load so turbolinks-android fails to inject. The logs says: "Error instantiating turbolinks_bridge.js - resetting to cold boot.". After the failed injection the adapter doesn't work either. None of the callbacks except for `onPageFinished` seem to run.

I've fixed it by replacing `head(status: 401)` with something like `render('layouts/application', layout: false, status: 401)`. Page loads, Turbolinks gets injected and immediately runs the `requestFailedWithStatusCode` callback as expected.
