### ISSUE TITLE
Double call to TurbolinksHelper.encodeUrl

### ISSUE THREAD

**Issue by coorasse** [turbolinks/turbolinks-android#14]
In TurbolinksSession.java, in `visitCurrentLocationWithTurbolinks` the location is encoded and passed to `visitLocationWithAction` where is encoded again. resulting in a bad encoding for params and consequentially a bad request error on server.

**Comment by lateplate** [comment]
Oops, sorry about that! We'll get this fixed up for the next release.

**Comment by lateplate** [comment]
This is fixed in master and will go out in 1.0.2 (targeting next week for that).

**Comment by lateplate** [comment]
Version 1.0.2 with this bug fix in place has been published. Thanks!
