### ISSUE TITLE
Form POST "refreshes" back to previous page

### ISSUE THREAD

**Issue by michiels** [turbolinks/turbolinks-android#15]
I'm using this wrapper on a Rails 5.0.0.beta3 app. Whenever I submit a form, I see the resulting form page/redirect, but then the wrapper seems to "refresh" back to the original form page.

Here's a GIF that illustrates this. 

![device-2016-04-07-114146](https://cloud.githubusercontent.com/assets/42268/14347197/19b49b38-fcb6-11e5-935d-8efea1a98ccf.gif)

The login form is submitted, the resulting "error" is rendered (this is a regular render by my `SessionsController`) but then the view flicks back to the original page. Do I need some logic in my Rails app to handle this case? This also happens on other regular form submits.

Thanks for any help!

**Update**

A bit more information as to what happens on the Rails end (see log below). It seems that my "/" gets re-visited after rendering the `SessionsController#new` (which should be the last call)

```
Started POST "/users/sign_in" for 192.168.1.18 at 2016-04-07 11:49:15 +0200
Processing by SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"2VH6MaPqltonjhBww5nEc4R+xeWWLycrT+v9oX6LOrYhcvLl+BNe7ppjD8zayr6TDFBwpfaR7rN5T8Sa5POI0w==", "user"=>{"email"=>"", "password"=>"[FILTERED]", "remember_me"=>"1"}, "commit"=>"Inloggen"}
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)


Processing by SessionsController#new as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"2VH6MaPqltonjhBww5nEc4R+xeWWLycrT+v9oX6LOrYhcvLl+BNe7ppjD8zayr6TDFBwpfaR7rN5T8Sa5POI0w==", "user"=>{"email"=>"", "password"=>"[FILTERED]", "remember_me"=>"1"}, "commit"=>"Inloggen"}
  Rendered devise/sessions/new.html.erb within layouts/sessions (1.5ms)
  Rendered application/_mixpanel.html.erb (0.5ms)
  Rendered application/_javascript.html.erb (80.8ms)
  Rendered layouts/application.html.erb (118.8ms)
Completed 200 OK in 131ms (Views: 129.4ms | ActiveRecord: 0.0ms)


Started GET "/" for 192.168.1.18 at 2016-04-07 11:49:15 +0200
Processing by SessionsController#new as HTML
  Rendered devise/sessions/new.html.erb within layouts/sessions (1.6ms)
  Rendered application/_mixpanel.html.erb (0.4ms)
  Rendered application/_javascript.html.erb (99.7ms)
  Rendered layouts/application.html.erb (140.1ms)
Completed 200 OK in 154ms (Views: 152.2ms | ActiveRecord: 0.0ms)

```

**Comment by michiels** [comment]
Added extra development log info to the issue's description.

**Comment by h1u2i3** [comment]
```
Started POST "/users/sign_in" for 192.168.1.18 at 2016-04-07 11:49:15 +0200
Processing by SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"2VH6MaPqltonjhBww5nEc4R+xeWWLycrT+v9oX6LOrYhcvLl+BNe7ppjD8zayr6TDFBwpfaR7rN5T8Sa5POI0w==", "user"=>{"email"=>"", "password"=>"[FILTERED]", "remember_me"=>"1"}, "commit"=>"Inloggen"}
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)
```
maybe something wrong with your rails code in `SessionsController`, because your post to `/users/sign_in` return 401 Unauthorized.
it seem you use the `devise` gem, and the SessionController#create should not add `before_action :authenticate_user!`, it must be public access.

**Comment by michiels** [comment]
@h1u2i3 I think you're right. I didn't expect that the wrapper would re-render the original request when a 401 with content was rendered.

Also, I did not realize that the Turbolinks form now only work on remote forms. After changing all the forms in my app to remote, the requests came back correctly.

**Comment by lateplate** [comment]
Sorry for the delay in responding @michiels, though it looks like you've already found the best solution!

There's a bit more detail on [the iOS adapter repo](https://github.com/turbolinks/turbolinks-ios/issues/25#issuecomment-206362621) discussing a similar issue.

**Comment by michiels** [comment]
@lateplaye You bet! I can close this issue now, but you can also keep it around for other users or I could turn it into a PR that puts 3 lines in the README about this?

**Comment by lateplate** [comment]
An addition to the README would be a welcome addition -- thanks!

**Comment by h1u2i3** [comment]
@michiels Turbolinks-android only work for `get` links and the [redirect_to](https://github.com/turbolinks/turbolinks-rails/blob/master/lib/turbolinks/redirection.rb#L9) method, or just the `Turbolinks.visit` in JS.

**Comment by michiels** [comment]
@h1u2i3 Yeah! Found that out :+1: Thanks! See my previous comments with @lateplate too.

**Comment by lateplate** [comment]
@michiels Feel free to add to the README. I'm going to close this for now. Thanks!
