### ISSUE TITLE
Comunicate with the webView

### ISSUE THREAD

**Issue by hecbuma** [turbolinks/turbolinks-android#16]
Hi, I'm playing around with the demo app and trying to integrate it with another project. So far I was successful to do it with turbolinks-ios and now with turbolinks-androd I'm struggling to communicate the javascript in the server with webview. I saw the part of custom javascript interface in the docs, but  it's not clear to me. 

Could someone elaborate about this?

**Comment by lateplate** [comment]
If you can provide a code snippet I can point you in the right direction.

Broadly speaking, you can call Javascript on any page one of two ways:

1. Use the [convenience methods](https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksSession.java#L628-L639) to call a function or run any raw Javascript
1. Get a [reference to the WebView itself](https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksSession.java#L608-L610) and call Javascript using the normal Android pattern of firing `.loadUrl('javascript:foo()')`
