### ISSUE TITLE
Redirect target landing doesn't invoke TurbolinksSession.visit ?

### ISSUE THREAD

**Issue by homerlex** [turbolinks/turbolinks-android#21]
Rails 5 / Turbolinks 5.0.0

We are playing with turbolinks-android with a Rails app (we just upgraded to Rails 5) and noticed an undesirable behavior (or non-behavior) with redirects.

Take the following scenario:

- User is on our homepage and logged in.
- They click on a "logout" link.  When they click on this link the TurbolinksSession.visit method is called and the TurbolinksSession.location property it set to /logout.
In the rails controller that handles the logout request we simply clear the user's session and redirect them back to the homepage:

```
def logout
  session.clear
  redirect_to root_path
end
```

- When this redirect is executed I notice that the TurbolinksSession.visit method is not called.  So, the TurbolinksSession.location property is still set to /logout.

- At this point the user can submit a form (on the home page) that results in us starting an oauth dance to log the user in.  Again, the TurbolinksSession.location is still set to /logout since visit doesn't get called on this post.  

- When the user returns to our site (after oauth) they get directed to our homepage.  However, TurbolinksSession.visitCurrentLocationWithTurbolinks gets fired and since the current value of TurbolinksSession.location is /logout they get directed to logged out again.  

I played with redirect_to a bit to make sure it had nothing to do with getting logged out.  Anytime we are navigated to a page via redirect_to the TurbolinksSession.location is not set the page we ended up on.

Is there something that need to be done explicitly so that TurbolinksSession.location is set properly in our scenario so that the user ends up on the correct page after returning from authenticating?

**Comment by chloerei** [comment]
I think http redirect will break Turbolinks, try submit logout via remote link(ujs), and redirect_to will call Turbolinks. visit automatically.

**Comment by lateplate** [comment]
Hey there. Sorry for not getting back to you sooner. A few potential things to consider:

1. @chloerei's solution should work. A submit via XHR/remote ought to do the trick I believe.
2. If it's a known scenario like logout, you could also [reset the entire Turbolinks Android session](http://turbolinks.github.io/turbolinks-android/javadoc/com/basecamp/turbolinks/TurbolinksSession.html#resetDefault--). Not something you'd want for a non-logout, but may be an option here.
3. The core Turbolinks team is planning [some general fixes around location state for 5.1](https://github.com/turbolinks/turbolinks/issues/88#issuecomment-237586859).
