### ISSUE TITLE
Specify minimum Android API Version in the Readme

### ISSUE THREAD

**Issue by risinglf** [turbolinks/turbolinks-android#22]
First of all, thanks guys for this great project!

I cannot find the minSdkVersion on the README so I checked the Grandle file from here: 
https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/build.gradle

and for what I can understand the minSdkVersion is set to 19. Can you please confirm it?

I think it could be useful to specify to the minSdkVersion in the README as for turobolinks-ios

Thanks

**Comment by lateplate** [comment]
Hi. That's correct -- the minimum SDK is 19. Sorry that wasn't make clear up front.

It'd be great to add that to the [README in the prerequisites section](https://github.com/turbolinks/turbolinks-android#prerequisites) if you'd like to cut a pull request. Thanks!

**Comment by lateplate** [comment]
HI @risinglf, I added the minSdkVersion prereq to the [README](https://github.com/turbolinks/turbolinks-android#prerequisites). Thanks for pointing that out.

**Comment by risinglf** [comment]
Sorry @lateplate for the delay, and thank you very much!

**Comment by lateplate** [comment]
👍
