### ISSUE TITLE
How to use with the Crosswalk Project?

### ISSUE THREAD

**Issue by candrews** [turbolinks/turbolinks-android#23]
I'd really like to use the [Crosswalk Project](https://crosswalk-project.org/) with Turbolinks Android  - but there doesn't seem to be a way to do so. Is there such a way that could be added to the README.md, or could a way be added?

**Comment by lateplate** [comment]
Hi. I don't know much about Crosswalk, but it appears to be its own custom WebView stack, so I don't think it would be compatible.

Turbolinks Android is intended to be used with a Turbolinks-enabled site, and we use a standard Android WebView and manage its lifecycle.
