### ISSUE TITLE
Include proguard configuration in the library

### ISSUE THREAD

**Issue by candrews** [turbolinks/turbolinks-android#29]
This library should include proguard configuration so that apps that use it and have proguard minify enabled "just work" without further configuration. (Without further configuration, the @JavascriptInterface methods get removed which is obviously problematic.)

The consumerProguardFiles directive should be used in the build.gradle. See https://github.com/googlesamples/android-testing-templates/tree/master/AndroidTestingBlueprint/module-android-library as an example of how to set this up.

**Comment by lateplate** [comment]
@candrews If you'd like to make a pull request with the proposed changed, happy to review it and bring it in. Thanks.

**Comment by candrews** [comment]
Thanks! I'll get on it :-)

**Comment by lateplate** [comment]
Awesome, much appreciated!
