### ISSUE TITLE
Issue with Android 7 (nougat)

### ISSUE THREAD

**Issue by LILkillaBEE** [turbolinks/turbolinks-android#42]
HI,

I'm having issue with Android 7 (nougat)...
After I build stack of few turbolinks activities (three for example) and when I'm going back, at least one activity would be blank when it become active (resume from back stack).
On previous versions of android everything seems to be fine.

Do you have some advice?

Thank you.

**Comment by joemasilotti** [comment]
We are experiencing this issue as well after updating to v1.0.3.

**Comment by lateplate** [comment]
We've been using 1.0.3 on 7.0 as well, but haven't been encountering back stack issues. Hard to say what the issue might be without a little more detail.

Could either of your provide logs from the Android console, your WebView (on 7.0, Chrome version) video/screenshot, or anything else supporting that could help?

With reliance on Google's build tools and support library, it's certainly possible there are differences in OS versions, perhaps some kind of animation timing. But for the most part, we're generally just working with WebView (Chrome on 7.0) so this is definitely odd.

**Comment by lateplate** [comment]
Closing. If you have any more info to provide, happy to reopen. As I mentioned, we haven't seen issues running on 7.x.
