### ISSUE TITLE
HOWTO: Set a custom user-agent string?

### ISSUE THREAD

**Issue by vlucas** [turbolinks/turbolinks-android#46]
The iOS version of Turbolinks provides an example on how to change the user-agent string:
https://github.com/turbolinks/turbolinks-ios#setting-a-custom-user-agent

I don't see anything like this for this Android project, and as an Android newbie, am not sure where to start. Digging through the source did not reveal any built-in Turbolinks method to do this - is there some way to pass in some other custom configuration object like with iOS?

Please help! I have my iOS app working flawlessly - now I am trying to figure out Android. :)

**Comment by lateplate** [comment]
Hi. You have [full access to the WebView object](https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksSession.java#L633) we create.

So you can retrieve the WebView from Turbolinks, [get its `WebSettings`](https://developer.android.com/reference/android/webkit/WebView.html#getSettings()), then [set the user agent](https://developer.android.com/reference/android/webkit/WebSettings.html#setUserAgentString(java.lang.String)).

**Comment by vlucas** [comment]
Thank you @lateplate. This pointed me in the right direction, and I was able to figure it all out and get it working! 👍

**Comment by chamnap** [comment]
@lateplate, maybe update the README the same way as `tuborlink-ios`? It's good for VERY novice android developer like me. :)

**Comment by lateplate** [comment]
@chamnap Happy to review any suggested updates to the README if you'd like to put together a pull request.

**Comment by gbuesing** [comment]
I'm setting the User-Agent in the demoapp, in ```onCreate``` right before executing the visit, like so:

```java
TurbolinksSession.getDefault(this).getWebView().getSettings().setUserAgentString("DemoApp");
```

Works fine in the simulator, however, when I deploy to my device (a Blu R1 HD running Android 6.0), the initial web request times out, and I see the following error in the Android Monitor:

```
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 28259
```

Googled around for this; best I can tell, seems like it might be a race condition? Can't figure out a a workaround for this, though.

**Comment by gbuesing** [comment]
Update: no longer having this issue, and I have no idea why not. Before, was very consistently failing when I had the call to setUserAgentString() in the app, and succeeding when I removed it. A few hours later, after not changing anything, it wasn't giving me an issue. Who knows. I think I restarted Android Studio, maybe that did something...

Anyway, that's how you set the user agent. Hopefully someone else will find that code sample helpful.

**Comment by lateplate** [comment]
@gbuesing Thanks for the update. I was about to respond but heard through the grapevine that it magically started working again. 

I really have no idea why that would be. We effectively do the same thing in Basecamp -- get the standard Android webview object from `TurbolinksSession`, then set it through Android's standard method `WebView.setUserAgentString()`.

Only random thing I could think of is perhaps the WebView component on your device was out of date, and it updated in the background? Still, I'd expect the user-agent setting to work regardless, so just shooting in the dark.
