### ISSUE TITLE
How i can Native Navigation Menu for Android

### ISSUE THREAD

**Issue by WaKeMaTTa** [turbolinks/turbolinks-android#47]
How i can native navigation menu for Android, passing some params or json from the web? :question:

**Comment by lateplate** [comment]
Can you give more details/an example of what you're trying to do? Most likely it's beyond the scope of the library, but we'd need more detail to start.

**Comment by WaKeMaTTa** [comment]
Let me explain.

Let's say we created an app with turbolinks-android, and users they log in.

This user has a role, for example `moderator`.

And the users who have this role (moderator), has 1 extra option in the menu (toolbar).

**Comment by lateplate** [comment]
I'd recommend reviewing the [Android documentation for menus](https://developer.android.com/guide/topics/ui/menus.html). Turbolinks Android doesn't manage anything like that -- it's strictly responsible for maintaining a Turbolinks session on a shared webview.
