### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference

### ISSUE THREAD

**Issue by cmrichards** [turbolinks/turbolinks-android#48]
I've just cloned this repo, opened the demoapp in Android Studio, updated the missing dependencies, ran the sinatra app, and then ran the android app.

The first page opens fine, but when I click on the "Open a new activity" link it crashes about 80% of the time and this is the error in the console  : 

> 09-30 10:27:23.582 12827-12827/com.basecamp.turbolinks.demo D/TurbolinksLog: visit called
> 09-30 10:27:23.583 12827-12827/com.basecamp.turbolinks.demo D/TurbolinksLog: TurbolinksSession background: null
> 09-30 10:27:23.583 12827-12827/com.basecamp.turbolinks.demo D/TurbolinksLog: showProgress called
> 09-30 10:27:23.583 12827-12827/com.basecamp.turbolinks.demo D/TurbolinksLog: Visiting current stored location: http://0.0.0.0:9292/one
> 09-30 10:27:23.586 12827-12827/com.basecamp.turbolinks.demo E/InputEventReceiver: Exception dispatching input event.
> 09-30 10:27:23.587 12827-12827/com.basecamp.turbolinks.demo D/AndroidRuntime: Shutting down VM
> 09-30 10:27:23.588 12827-12827/com.basecamp.turbolinks.demo E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                               Process: com.basecamp.turbolinks.demo, PID: 12827
>                                                                               java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
>                                                                                   at android.view.ViewGroup.canViewReceivePointerEvents(ViewGroup.java:2316)
>                                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1581)
>                                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
>                                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
>                                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
>                                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
>                                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
>                                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
>                                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
>                                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
>                                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
>                                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
>                                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
>                                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
>                                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
>                                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
>                                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
>                                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
>                                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
>                                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
>                                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
>                                                                                   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
>                                                                                   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1640)
>                                                                                   at android.view.View.dispatchGenericMotionEvent(View.java:8552)
>                                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2377)
>                                                                                   at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1729)
>                                                                                   at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2778)
>                                                                                   at android.support.v7.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:73)
>                                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2344)
>                                                                                   at android.view.View.dispatchPointerEvent(View.java:8668)
>                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
>                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
>                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
>                                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
>                                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
>                                                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
>                                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
>                                                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
>                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
>                                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
>                                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
>                                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
>                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
>                                                                                   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
>                                                                                   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
>                                                                                   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
>                                                                                   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
>                                                                                   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
>                                                                                   at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
>                                                                               	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventRece
> 09-30 10:27:25.031 12827-12827/com.basecamp.turbolinks.demo I/Process: Sending signal. PID: 12827 SIG: 9

I don't know if it's relevant, but there are also lots of these errors that happen all the time, including when the app first opens and I go to different pages.  It doesn't seem to affect anything :

> 09-30 10:27:23.566 12827-12870/com.basecamp.turbolinks.demo E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000b44
> 09-30 10:27:23.572 12827-12870/com.basecamp.turbolinks.demo E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000bd0
> 09-30 10:27:23.574 12827-12870/com.basecamp.turbolinks.demo E/eglCodecCommon: **** ERROR unknown type 0x0 (glSizeof,73)
> 09-30 10:27:23.576 12827-12870/com.basecamp.turbolinks.demo E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000b44
> 09-30 10:27:23.579 12827-12870/com.basecamp.turbolinks.demo E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000bd0
> 09-30 10:27:23.580 12827-12870/com.basecamp.turbolinks.demo E/eglCodecCommon: **** ERROR unknown type 0x0 (glSizeof,73)

**Comment by cmrichards** [comment]
Doesn't happen on a real device

**Comment by WaKeMaTTa** [comment]
@cmrichards which emulator do you use?

**Comment by cmrichards** [comment]
I start it using AVD : 

Nexus 5 
Android 5.1.1 - API Level 22   <---- Maybe that's it?
Item Atom (x86)

**Comment by WaKeMaTTa** [comment]
I'm using GenyMotion with Nexus 5, Android 5.1.0, API 22 and it works fine.

Give a try [genymotion](https://www.genymotion.com/) if you want.

**Comment by cmrichards** [comment]
I will, thanks
