### ISSUE TITLE
GET request after a post request

### ISSUE THREAD

**Issue by cmrichards** [turbolinks/turbolinks-android#49]
I'm using the Android demo app code provided with this repo to connect to a Rails 5 app I've just created.

After I make a POST request and then redirect, turbolinks only shows the redirected page for a fraction of a second before making another GET request to the original page I was on (the form page) and shows it.  This doesn't happen when I use a normal browser.

In detail : 

1.  I open a form - GET request to /jobs/new
2.  Submit the form - POST request to /jobs
3.  I redirect to /jobs/index  - (redirect_to jobs_path) GET request
4.  The system shows /jobs/index for a fraction of a second...
5   ... and then performs another GET request to /jobs/new and displays an empty form again

Is there something obvious I'm missing?

**Comment by cmrichards** [comment]
If I add "remote: true" to my form it works.  But should I have to do this?

```
= simple_form_for @job, remote: true do |f|
  = f.input :company
  = f.input :address
  = f.input :job_date, order: [:day, :month, :year]

  = submit_tag "Create", class: "btn btn-primary"
```

**Comment by WaKeMaTTa** [comment]
I did try `remote: true` but it dosen't work always. :confused:

**Comment by lateplate** [comment]
Submitting the form via xhr is preferred for now. HTTP redirects I believe are causing some issues currently in core Turbolinks, but [it's slated to be address in 5.1](https://github.com/turbolinks/turbolinks/issues/88).
