### ISSUE TITLE
Can't set custom header data for URL visits.

### ISSUE THREAD

**Issue by jonlange** [turbolinks/turbolinks-android#54]
I have an application that requires header data to be set from the device on each URL call. Is there any way I can do this in the existing version of turbolinks-android? The only thing I can think of is calling a javascript function using .runJavascript().

I noticed that the Android WebView has a method to do exactly what I am looking for, and you could just overload the .visit() function like this: 

    /**
     * <p><b>REQUIRED</b> Executes a Turbolinks visit and sets supplied header parameters.
     * Must be called at the end of the chain --
     * all required parameters will first be validated before firing.</p>
     *
     * @param location The URL to visit.
     * @param additionalHttpHeaders Additional headers to be used in URL request.
     */
     public void visit(String location, Map<String, String> additionalHttpHeaders) {
          TurbolinksLog.d("visit called");

          this.location = location;

          validateRequiredParams();

          if (!turbolinksIsReady || webViewAttachedToNewParent) {
	          initProgressView();
          }

          if (turbolinksIsReady) {
	          visitCurrentLocationWithTurbolinks();
          }

          if (!turbolinksIsReady && !coldBootInProgress) {
	          TurbolinksLog.d("Cold booting: " + location);
	          webView.loadUrl(location, additionalHttpHeaders);
          }

          // Reset so that cached snapshot is not the default for the next visit
          restoreWithCachedSnapshot = false;

     }

But this would require turbolinks-android to have a minimum API level of 8. 

Any ideas on how to achieve this would be greatly appreciated. 

Thanks,

**Comment by WaKeMaTTa** [comment]
```java
@Override
    public void visitCompleted() {
        webView.post(new Runnable() {
            public void run() {
                String title = webView.getTitle();
                mToolbar.setTitle(title);
            }
        });
    }
```

**Comment by lateplate** [comment]
@jonlange Sorry, this isn't supported right now, but it's a reasonable need.

The issue might be that only the initial `WebView.loadUrl()` would be under our control. Every subsequent visit would be through Turbolinks, not a `WebView.loadUrl()`.

Currently Turbolinks core doesn't have a drop-in function to change headers. You'd need to [observe events and set your headers](https://github.com/turbolinks/turbolinks#setting-custom-http-headers). You could do this with JS on the web side, but could also perhaps do this by injecting your own JavaScript into the Turbolinks WebView to do this.

**Comment by jonlange** [comment]
@lateplate Thanks for your feedback. I see your point regarding Turbolinks core, I will stick to calling my JavaScript function, and can set the headers by handling the `turbolinks:request-start` event.

**Comment by strzibny** [comment]
@lateplate may I ask how do you go about sending JWT for authentication? Or Basecamp does not use tokens for Android auth? Really curious about this....
