### ISSUE TITLE
android adapter vs cordova

### ISSUE THREAD

**Issue by kirantpatil** [turbolinks/turbolinks-android#55]
Hello,

I would like to know why do we need to use android adapter since we have [apache Cordova](https://cordova.apache.org/) ?

Kiran.

**Comment by kirantpatil** [comment]
Sorry, I now edited my question.

**Comment by lateplate** [comment]
I'm not sure. Offhand I don't see any reason you'd use both. Turbolinks and Cordova have no affiliation and without any context of what you're trying to accomplish, it's hard to say how they might work together. 

I recommend giving the [Turbolinks Documentation](https://github.com/turbolinks/turbolinks) a read first.
