### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by hgani** [turbolinks/turbolinks-android#56]
Hi,

Is there any way we can clear cached pages?

I'd like to clear the cache whenever the user logs out.

Thanks

**Comment by lateplate** [comment]
We're using a standard webview under the hood. So you can use your TurbolinksSession to get the WebView, then [clear its cache](https://developer.android.com/reference/android/webkit/WebView.html#clearCache(boolean)).

Something similar to this (depending on how you're getting your session) should work:

`TurbolinksSession.getDefault(context).getWebView().clearCache(true)`

**Comment by hgani** [comment]
Great, thanks for the quick response.
