### ISSUE TITLE
ACTION_ADVANCE etc. constants should be public

### ISSUE THREAD

**Issue by elsurudo** [turbolinks/turbolinks-android#59]
I am referring to [these](https://github.com/turbolinks/turbolinks-android/blob/a25b9752e682415e4e5dc7b57e7c0aca79ee0288/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksSession.java#L60)

Is there a reason they are not public? As it is now, we need to compare the action with strings, which isn't ideal for maintenance and refactoring.

**Comment by lateplate** [comment]
They certainly could be, I don't see a problem with that. Happy to review a PR.
