### ISSUE TITLE
Turbolinks triggers :load twice and make Facebook SDK stop working

### ISSUE THREAD

**Issue by lucasfeliciano** [turbolinks/turbolinks-android#61]
We was experiencing only on Android devices an issue which the `load` event was being triggered twice. This behaviour was not happening on iOS or Web environments.

After debugging we realised that an error related to `webView.visitLocationWithActionAndRestorationIdentifier` was being thrown in the chrome console ( debugging android ) and we thought that`visitCurrentLocationWithTurbolinks()` was being called manually somewhere.

So we found that it was here:

https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksSession.java#L562

After commenting this line we fixed the issue, but my question is:
Do we have any collateral effect by doing that? For now we are not experiencing any problems but since I'm not an android developer I can assure that removing this line will not impact in another part of the code.

Do any one knows about it?

**Comment by lateplate** [comment]
@lucasfeliciano you're correct. The initial boot does fire twice (once via WebView, once via TL). This is my main sore spot with the code. We had quite a bit of trouble relying on WebView to do the right thing under all conditions, so firing through TL, which duplicative, was the most reliable. I'm hoping to look at this as part of a bigger refactor in the new year.

Commenting it out might work for your needs, but it's hard to say for sure how reliable it will be. It will only fire on the first cold boot, so your exposure to any issues would at least be limited.

**Comment by tinOfBeans** [comment]
Is there an update on this issue?
