### ISSUE TITLE
Accessing user's location

### ISSUE THREAD

**Issue by aponcz** [turbolinks/turbolinks-android#62]
We are unable to get the user's GPS location in the turbolinks-android app, however, we are able to get their location in the turbolinks-ios app.  On the rails server we are using the following JavaScript for accessing location data:

`navigator.geolocation.getCurrentPosition(callback);`

In our Android app we are requesting location permission:

src/main/AndroidManifest.xml:
`<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>`

Are we missing an additional configuration or is there a workaround to get the user's location?

**Comment by lateplate** [comment]
This isn't anything specific related to Turbolinks Android. Under the covers, we use the standard Android WebView. If you're having trouble running JS, it's something related to the WebView/JS implementation of whatever OS version you're using, not this lib.

I'd recommend trying a vanilla webview in a test app (remove Turbolinks Android from the equation), check your logs, and try to see what's going on.
