### ISSUE TITLE
I get html request in stead of xhr

### ISSUE THREAD

**Issue by WaKeMaTTa** [turbolinks/turbolinks-android#65]
Hi 

I have an issue using my code blow. The issue is when `uploadingFile` is `true` and i submit my form, the request i get in the server is `Content-Type: text/html` in stead of `xhr`.

Help please.

```
@Override
protected void onRestart() {
  super.onRestart();

  if (uploadingFile == true) {
    TurbolinksSession.getDefault(this)
      .activity(this)
      .adapter(this)
      .view(turbolinksView);
  } else {
    // Since the webView is shared between activities, we need to tell Turbolinks
    // to load the location from the previous activity upon restarting
    TurbolinksSession.getDefault(this)
      .activity(this)
      .adapter(this)
      .restoreWithCachedSnapshot(true)
      .view(turbolinksView)
      .visit(location);
  }
}
```

This is the result:

Hi 

I'm using Turbolinks 5 and i have a android application.

I have an issue using my code blow in android. 

The issue is when `uploadingFile` is `true` and i submit my form, the request i get in the server is `Content-Type: text/html` in stead of `xhr`.

    @Override
    protected void onRestart() {
      super.onRestart();

      if (uploadingFile == true) {
        TurbolinksSession.getDefault(this)
          .activity(this)
          .adapter(this)
          .view(turbolinksView);
      } else {
        // Since the webView is shared between activities, we need to tell Turbolinks
        // to load the location from the previous activity upon restarting
        TurbolinksSession.getDefault(this)
          .activity(this)
          .adapter(this)
          .restoreWithCachedSnapshot(true)
          .view(turbolinksView)
          .visit(location);
      }
    }

Help please. thanks.

![screenshot](https://cloud.githubusercontent.com/assets/3450257/22184296/08f05dde-e0cf-11e6-804b-7ae6aa2e444c.png)

related to https://github.com/turbolinks/turbolinks-android/issues/53#issuecomment-268867231

**Comment by lateplate** [comment]
My guess is this is some combination of how you're submitting the form and how you're resuming.

In the Android code, when `uploading==true`, you're not calling a `visit()`. So the Turbolinks WebView is effectively just sitting there. 

If you're expecting a different response type, that would need to be resolved on the Rails side.

**Comment by WaKeMaTTa** [comment]
Thanks for the fast response @lateplate . I found this is not an issue of `turbolinks-android` is an issue of `turbolinks`.

This is the same issue i have https://github.com/turbolinks/turbolinks/issues/88
