### ISSUE TITLE
Unpredictable life of a TurbolinksSession and the issue of JavascriptInterfaces

### ISSUE THREAD

**Issue by kassim** [turbolinks/turbolinks-android#66]
So the rule for `WebView.addJavascriptInterface` is that you must call it before you call `WebView.loadUrl` otherwise it won't be injected.

Lets say we have a single MainActivity class in your app that injects an interface during `onCreate`. 
Your app loads, Turbolinks boots and is now "ready". You then kill the app with your back button - so the Application instance is still alive, the TurbolinksSession instance is maybe still alive (it can die in the background but this isn't guaranteed). 
You then open the app again, with the TurbolinksSession from before still alive, your code calls `TurbolinkSesssin.getInstance(this).addInterface` but because TurbolinksSession is still "ready", `WebView.loadUrl` never gets called

Possible solution: if addJavascriptInterface is called you reset the state so that `loadUrl` is called on the next `visit`

At the least the documentation should reflect this possible issue as it certainly has caused issues for us. 

My solution has been to make my interface object persist like the TurbolinkSession as a singleton and have activities attach/detach to it but I think it would be bad practice to force such an implementation

**Comment by kassim** [comment]
actually... it seems the TurbolinkSession.addJavascriptInterface() won't allow the JavascriptInterface to be added on second launch anyway - despite the docs saying "Names of interfaces must be unique, or they will be **overwritten** in the library's map."

**Comment by lateplate** [comment]
Please feel free to PR the documentation miss. Thanks!

**Comment by scruff311** [comment]
@kassim did you come up with a solution for this issue? We have come to the same realization and thought of the same solution as you (singleton interface with attach/detach activity), but haven't gone down that road yet hoping there was a simpler solution.

We have altered the `TurbolinksSession` to allow for overwriting a `JavascriptInterface`, but we find that you need to force the `webView` to reload after adding/changing the interface for the connection to work. This means that anytime you navigate to a new view i.e. create a new activity with a new location, you need to force the `webView` to refresh in order for the new `JavascriptInterface` to work. This of course is not a solution.
