### ISSUE TITLE
Turbolinks-android and OmniAuth

### ISSUE THREAD

**Issue by dachdecker** [turbolinks/turbolinks-android#72]
First a big thanks to the team for putting together and maintaining this excellent library. I was amazed how easy it was to get almost entire functionality of an existing web app. My only missing link at the moment is OmniAuth. 

Currently our Turbolinks web app offers users a link generated by the OmniAuth gem pointing to the app's "/users/auth/google_oauth2", which is then picked up by the gem and begins the callback that isn't captured by turbolinks. For users in the alpha android app at the moment, clicking the button never generates the prompt to enter log in details.  

There has already been a similar discussion on the [turbolinks-ios library](https://github.com/turbolinks/turbolinks-ios/issues/66), but I'm very new to Android development and can not easily translate this to Java. 

I'm also conscious of Google's decision to [terminate the access of WebViews to OAuth. ](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html)

I've gone as far as capturing the request to the specific url, but how to treat it seamlessly and return the user to the turbolinks session is escaping me:

```
public void visitProposedToLocationWithAction(String location, String action) {
        Intent intent = new Intent(this, MainActivity.class);
        intent.putExtra(INTENT_URL, location);
        if (location.equals("https://example.com/users/auth/google_oauth2")) {
            Log.d("linkclicked", "oauthcaptured");
            //handle OAuth
        } else {
            this.startActivity(intent);
        }
    }
```

With something as ubiquitous as OAuth, I'm surprised I haven't come across examples of how to handle this cleanly while using turbolinks-android. Any advice and examples would be greatly appreciated.

**Comment by lateplate** [comment]
Hello!

From what I can tell, it seems like you're running into what [Zach described in the iOS issue](https://github.com/turbolinks/turbolinks-ios/issues/66#issuecomment-248328944) -- that whatever HTML the OmniAuth gem generates doesn't use Turbolinks. So the link to click the button is not firing Turbolinks, and therefore `visitProposedToLocationWithAction` is never being called.

You  may need to do something like Zach suggested.

1. Create a separate webview/activity for the OAuth page
2. Intercept the OAuth callback as necessary and process/save authentication as appropriate for your app
3. Open your app's webview and fire a TL visit, setting whatever headers/cookies necessary for authentication.

Hope that helps!
