### ISSUE TITLE
Android user agent

### ISSUE THREAD

**Issue by amtheguy** [turbolinks/turbolinks-android#74]
I've gone through the documentation and i can't seem to find how to configure a custom user agent for android. 

This feature exist for ios. Is there any work around for android?

**Comment by lateplate** [comment]
You have full access to the `WebView` object itself, so you can retrieve that from the `TurbolinksSession` and configure it as needed.

For example, if your'e using the default session:

`WebView webView = TurbolinksSession.getDefault().getWebView()`

Once you have that, you can [set the user agent](https://developer.android.com/reference/android/webkit/WebSettings.html#setUserAgentString(java.lang.String)) as you normally would in Android.
