### ISSUE TITLE
Demo app back button fails

### ISSUE THREAD

**Issue by redhotvengeance** [turbolinks/turbolinks-android#75]
I'm getting started on Turbolinks for Android, and thought I'd start with the demo app. I'm running into an issue with the back button, however.

I'll spin up the demo app, tap `Open a new activity`, and the app successfully navigates to the `Page One` screen. If I then hit the phone's back button, it appears that `Page One` pops off the view stack and I return back to the welcome screen. However, the screen doesn't actually show up—it just stays gray. Pull-to-refresh pops a loading indicator, but it spins forever. However, if I change the phone orientation, the welcome screen appears, and I can successfully interact with it.

Should the demo app be working properly with the back button? Is this a bug? Or is additional code needed to use the back button with Turbolinks for Android.

My build is targeting 4.4, and I'm testing on 5.1.1.

**Comment by redhotvengeance** [comment]
I've found that I can get the back button to work properly if I override the `onRestart` method and add a call to the Turbolinks session:

```java
@Override
protected void onRestart() {
    super.onRestart();

    TurbolinksSession.getDefault(this)
            .activity(this)
            .adapter(this)
            .restoreWithCachedSnapshot(true)
            .view(turbolinksView)
            .visit(location);
}
```

I'm not sure if this is a workaround for a bug, or if this code is expected to enable proper back button usage. Since there's no mention of this in the docs or demo app, it feels like a bug to me, although I'm very new to Turbolinks on Android, so I'm only guessing at this point.

**Comment by lateplate** [comment]
Firing a visit with `restoreWithCachedSnapshot(true)` like you have is a good place to start. You can adjust for different scenarios with that as a starting point.

This is exactly what [the demo app code shows.](https://github.com/turbolinks/turbolinks-android/blob/master/demoapp/src/main/java/com/basecamp/turbolinks/demo/MainActivity.java#L47-L57)

**Comment by redhotvengeance** [comment]
@lateplate Thanks for the response! Apparently I missed that in the demo app...apologies for indicating that the app didn't work. I think at the point I made this ticket, I was copying/pasting between the demo and my own test as a means of experimenting, and I missed the `onRestart()` method.

May I respectfully suggest that the `onRestart()` sample is added to the README? I think all newcomers to Turbolinks will expect the "getting started" process to result in a properly functioning back button, and the README stops just short of the final step.

**Comment by lateplate** [comment]
Sure! Please feel free to create a pull request with suggested updates to the README and I'll be happy to review/merge up. Thanks!
