### ISSUE TITLE
Download image/file from url

### ISSUE THREAD

**Issue by Solidhan5000** [turbolinks/turbolinks-android#76]
Hello devs & experts,

We are using turbolinks-android as an extention for our Turbolink 5 enabled webapp. A working android app has been created and works really great!! 

However, there is one thing we can't get to work: We cannot download any images/files that normally work perfectly from the webapp. When clicking any download link, nothing happens. 

I have searched and tried several things. I have tried adding a downloadlistener but that does not work because it requires a WebView instead of a TurbolinksView. So far, we have not been able to solve this problem.

I would love some insight or ideas.

**Comment by lateplate** [comment]
> We cannot download any images/files that normally work perfectly from the webapp. When clicking any download link, nothing happens.

Sorry, without a code snippet or even better some logs, it's impossible to tell what might be happening. I'd start with [enabling logging in debug mode](http://turbolinks.github.io/turbolinks-android/com/basecamp/turbolinks/TurbolinksSession.html#setDebugLoggingEnabled-boolean-) and searching "Turbolinks" in your logs to see what might be happening.

Also, if it helps, you have [access to the `WebView`](http://turbolinks.github.io/turbolinks-android/com/basecamp/turbolinks/TurbolinksSession.html#getWebView--) if you need it.

If you can provide a little more info, I'm happy to reopen and take a look.

**Comment by Solidhan5000** [comment]
Hello lateplate,

My apologies. Here is my code. I was indeed trying to acces the `Webview` in order to get to the `setDownloadListener`
```

 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        turbolinksView = (TurbolinksView) findViewById(R.id.turbolinks_view);
        location = getIntent().getStringExtra(INTENT_URL) != null ? getIntent().getStringExtra(INTENT_URL) : BASE_URL;

        TurbolinksSession.getDefault(this)
                .activity(this)
                .adapter(this)
                .view(turbolinksView)
                .visit(location);

        TurbolinksSession.getDefault(this)
                .activity(this)
                .adapter(this)
                .view(turbolinksView)
                .getWebView().setDownloadListener(new DownloadListener() {

            @Override
            public void onDownloadStart(String url, String userAgent,
                                        String contentDisposition, String mimetype,
                                        long contentLength) {

                DownloadManager.Request request = new DownloadManager.Request(
                        Uri.parse(url));

                request.allowScanningByMediaScanner();
                request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED); //Notify client once download is completed!
                request.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS, "Name of your downloadble file goes here, example: Mathematics II ");
                DownloadManager dm = (DownloadManager) getSystemService(DOWNLOAD_SERVICE);
                dm.enqueue(request);
                Toast.makeText(getApplicationContext(), "Downloading File", //To notify the Client that the file is being downloaded
                        Toast.LENGTH_LONG).show();
            }
        });
    }

```
However nothing happens when I click a link. Even if I remove all the code and just leave the code below, I don't get a Toast message. It seems my link-clicking is not getting to this method.

```
TurbolinksSession.getDefault(this)
                .activity(this)
                .adapter(this)
                .view(turbolinksView)
                .getWebView().setDownloadListener(new DownloadListener() {

            @Override
            public void onDownloadStart(String url, String userAgent,
                                        String contentDisposition, String mimetype,
                                        long contentLength) {
                Toast.makeText(getApplicationContext(), "Downloading File", //To notify the Client that the file is being downloaded
                        Toast.LENGTH_LONG).show();
            }
        });  
```
 Am I doing it correctly?
