### ISSUE TITLE
How to view pdfs?

### ISSUE THREAD

**Issue by fiedl** [turbolinks/turbolinks-android#77]
If I link to a pdf on the server side and click the link in the android simulator, I see raw output rather than the rendered pdf.

How would I display pdfs with turbolinks-android?

<img width="524" alt="bildschirmfoto 2017-07-06 um 14 44 42" src="https://user-images.githubusercontent.com/1679688/27911678-33464fe6-625a-11e7-997d-39e93b0fa759.png">

Thank you very much in advance!

**Comment by WaKeMaTTa** [comment]
Capture the pdf URLs and open it with the normal browser.

**Comment by fiedl** [comment]
@WaKeMaTTa, thanks for the suggestion. I've already tried to open the url with an `Intent`.

```java
    @Override
    public void visitProposedToLocationWithAction(String location, String action) {

        if (location.endsWith(".pdf")) {
            Intent browserIntent = new Intent(Intent.ACTION_VIEW, android.net.Uri.parse(location));
            this.startActivity(browserIntent);
        } else {
            Intent intent = new Intent(this, MainActivity.class);
            intent.putExtra(INTENT_URL, location);
            this.startActivity(intent);
        }

    }
```

Unfortunately, this is rather clunky from the user perspective: 

- When clicking the link, the user is asked to choose a browser. I choose "Chrome".
- Chrome opens and downloads the file. One needs to confirm that Chrome is allowed to store files locally.
- Then a bar appears with a button to open the downloaded the file. If I miss to click "Open", the bar disappears and leaves me with a blank Chrome.
- If I click "Open", the pdf viewer opens the downloaded file. But if I click the "back" button, I'm ending up in an empty Chrome window rather than in my own application.

I could live with this solution if I could get Chrome or any other application to display the file inline.

Can I tell the intent that I need the file to be downloaded and opened with a pdf viewer?

**Comment by fiedl** [comment]
I've also tried to use [barteksc/AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer). But this tool can't download the file from a give url. I would have to download the file into a bytes array first. But I don't know how to do that.

Furthermore, what is the expected behaviour of an android user: To see the file inline or to have it opened with his favourite pdf viewer?

**Comment by lateplate** [comment]
Closing, since this is out of the scope of Turbolinks.

Your best bet would be to intercept the appropriate URLs and send them to a separate, non Turbolinks/WebView activity to render them for viewing.
