### ISSUE TITLE
How to fix this memory leak ?

### ISSUE THREAD

**Issue by gavinliu** [turbolinks/turbolinks-android#79]
<img width="499" alt="2017-07-26 13 46 08" src="https://user-images.githubusercontent.com/3281741/28606298-d8868102-7208-11e7-9033-6a504521d3a6.png">

```
    public TurbolinksSession activity(Activity activity) {
        this.activity = activity;

        Context webViewContext = webView.getContext();
        if (webViewContext instanceof MutableContextWrapper) {
            ((MutableContextWrapper) webViewContext).setBaseContext(this.activity);
        }

        return this;
    }
```

**Comment by lateplate** [comment]
Hi, thanks for posting this. We're aware of the issue and are investigating workarounds. Chrome 64 has forced the issue with a recent change.

**Comment by danielwestendorf** [comment]
Is this still a problem?

I'm investigating a memory leak and wondering if this is the cause.
