### ISSUE TITLE
how to create/use custom progressView/progressBar in place of default spinner?

### ISSUE THREAD

**Issue by daya** [turbolinks/turbolinks-android#80]
I am not getting the classic Turbolinks transition, without any intervening white page and with horizontal progress bar on top, on android. So **do I need my own progressView??**

I have this in my **MainActivity.java**

```java
            progressView = new ProgressBar(turbolinksView.getContext());
            TurbolinksSession.getDefault(this)
                    .activity(this)
                    .adapter(this)
                    .view(turbolinksView)
                    .progressView(progressView, R.id.indeterminateBar, 300)
                    .visit(location);
```
and this in my **activity_main.xml**

```xml
    <ProgressBar
        android:id="@+id/indeterminateBar"
        android:layout_width="wrap_content"
        style="@android:style/Widget.ProgressBar.Horizontal"
        android:layout_height="wrap_content"
        />

```
gradle settings are
```
compileSdkVersion 26
        minSdkVersion 19
        targetSdkVersion 22
```
when I run the above I get `IllegalArgumentException "A progress indicator view must be provided in your custom progressView."` so I tried 

```java
.progressView(progressView, progressView.getId(), 300)
```

but I still get `IllegalArgumentException "A progress indicator view must be provided in your custom progressView."`

**Obviously I am unable to instantiate the right `progressView`, my question what how do I get/create the right `progressView` ??**

**Comment by daya** [comment]
@lateplate any idea/input ?

**Comment by fabriziobertoglio1987** [comment]
Hello @daya .. how did you solve this issue? could you include a link to your github project? thanks

**Comment by fabriziobertoglio1987** [comment]
I solved this by following the instructions at https://stackoverflow.com/questions/46798464/on-android-turbolinks-how-to-create-custom-progressview-to-replace-default-spin

**Comment by lateplate** [comment]
The StackOverflow post that @fabriziobertoglio1987 points too looks correct to me. We (unclearly) expect there to be a wrapper view, and within that wrapper view, the `ProgressBar`. Apologies that isn't super clear. But the solution in the StackOverflow post should work fine.
