### ISSUE TITLE
TurbolinksView Debugging

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [turbolinks/turbolinks-android#83]
Hello,

Thanks a lot for the amazing library. Unluckily one of my pages is not working inside the TurbolinksView, but correctly behaving when I inspect the device running the WebApplication.

I needed to [debug the WebView](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews), but I thought that it was not possible with a TurbolinksView

`TurbolinksView` does not have the method `setWebContentsDebuggingEnabled();`, but by including the following code in my `MainActivity`

```
   WebView webview = new WebView(this);
        setContentView(webview);
        webview.setWebContentsDebuggingEnabled(true);
```
Allowed me to debug the `TurbolinksView` by opening the browser at chrome://inspect and inspect the html/css in my phone TurbolinksView Mobile App.

I decided to post this for further discussions, there is no actual issue to solve, but I believe it is a very useful tool.

Thanks a lot for the amazing project 
I am really enjoy it
Sorry for the eventual disturbance I am causing and I wish you happy holidays
Fabrizio

**Comment by lateplate** [comment]
Hi, thanks!

You should also be able to call `getWebView()` in `TurbolinksSession` to get a handle to the internal webview used by Turbolinks.

Once you have that, you should be able to set whatever attributes on the WebView you like, including `setWebContentsDebuggingEnabled`.

**Comment by fabriziobertoglio1987** [comment]
Hello @lateplate ,

Thanks a lot ... I really look forward to test this. This library is amazing! 
I did end up forking this turbolinks android project and it was pretty easy making the modification to adapt it for my app

https://github.com/HiKumho/milog-android

thanks again !
Fabrizio
