### ISSUE TITLE
IllegalArgumentException when attaching view

### ISSUE THREAD

**Issue by lidaamber** [turbolinks/turbolinks-android#87]
Got this when setting up Turbolinks session.

<img width="747" alt="2018-02-06 18 17 37" src="https://user-images.githubusercontent.com/10661484/35870348-20c7fd1a-0b6a-11e8-82ec-4e7d0c367bcb.png">

The turbolinks view was already initialized. I set up session in Activity like this:

```java
TurbolinksSession.getDefault(this).setDebugLoggingEnabled(false);

WebView webView = TurbolinksSession.getDefault(this).getWebView();
webView.getSettings().setUserAgentString(agentString);

TurbolinksSession.getDefault(this)
          .activity(this)
          .adapter(adapter)
          .view(turbolinksView)
          .visit(url);
```

When the bug was catched, version `1.0.7` was used. 
Any ideas? Maybe, I'm doing something wrong? Thanks for any help.

**Comment by lateplate** [comment]
Hi! This looks like the [same issue as this](https://github.com/turbolinks/turbolinks-android/issues/85).

Please try version 1.0.8 (which just shipped yesterday), which has a temporary workaround for this issue. It's not an ideal long-term fix, but it will get you by for the time being. Thanks!
