### ISSUE TITLE
How to show/hide the progressView manually?

### ISSUE THREAD

**Issue by scruff311** [turbolinks/turbolinks-android#93]
For certain URL paths I am loading the view with

`turbolinksSession.activity(this).adapter(this).restoreWithCachedSnapshot(false).view(turbolinksView).visit(BASE_URL + path);`

instead of creating a new Intent/Activity. I am doing this because these paths are accessed by the left side menu drawer so I want the view to be replaced, instead of having the visual effect of a new view coming onto the stack. There is some delay when waiting for the view to load, but there is no `progressView` appearing when I load the new URL in this fashion. I want to show it manually by calling `turbolinksView.showProgress()`, but that method is not public. I get the error **Cannot be accessed from outside package**. Any recommendations?

**Comment by lateplate** [comment]
Interesting use case, that isn't something we'd really considered. A couple options:

1. I don't think that method necessarily has to be private, we just didn't think there'd be a situation to manually control it. Happy to review a PR that makes it publicly accessible and check out what ramifications there might be.
1. You could also just place your own progress view over the `TurbolinksView` and manually manage it. It takes some of the responsibility away from TL and would be 100% in your control?

**Comment by scruff311** [comment]
Thanks, @lateplate. Mainly I'm just trying to make it so the content of the view changes in place instead of animating in a new `Activity` when an item in the left menu drawer is selected. I guess I could specify `FLAG_ACTIVITY_NO_ANIMATION` in the `Intent` instead? I'm an iOS dev trying to put together an Android app, so I am not super familiar with all the Android APIs.

As far as your #2 suggestion, I just want the progress view to look exactly like the TL one for consistency. Is there a way to grab that exact view?

**Comment by lateplate** [comment]
Yep, we do this occasionally too. There are a number of ways you could go about it (that intent flag could work, but I'm not 100% sure as I don't have it in front of me). 

We pass an extra, custom intent value that tells our next activity whether or not we want to animate. So we figure out if we want no animation, then call Activity's `overridePendingTransition(0,0)` so that it doesn't.
