### ISSUE TITLE
Successful Page Load with Blank Screen

### ISSUE THREAD

**Issue by jchunch** [turbolinks/turbolinks-android#94]
I recently started getting complaints from some of my app's users that pages are blank. We are using `v1.0.8` to load our mobile web page inside of our app. While debugging, I was able to reproduce the issue intermittently and noticed that we are getting callbacks that indicate the page was successfully loaded when it happened. Additionally, when a blank screen is loaded, it appears to be scrollable as if the content were displayed. 

I was wondering if your team had heard of anything like this before, and if so, whether there is anything we can do on our end to resolve. Thanks!

**Comment by lateplate** [comment]
I haven't heard of this before and we haven't seen any issues. Without having more detail, it _sounds_ like a rendering problem of a given page. If the WebView is calling back as `onPageFinished` (or similar) then we sort of have to take it at its word.

I'd suggest trying to narrow down the scenario. Are you able to reproduce with Turbolinks and a very simple page. Anything unique about the pages?

Also the fact that it's only happening intermittently seems to indicate it's not systematic with Turbolinks per se, but again, hard to say for sure.

**Comment by jchunch** [comment]
We are getting the `onPageFinished` callback, so it sounds like it is something on our end. Thanks for the quick response! I'll follow up if I figure out anything that might be helpful for other Turbolinks users.
